# Site settings
title: Your Book Title
description: A brief description of your book
url: "https://loganrios.github.io"
baseurl: "/book1"

# Author information
author: Logan Rios

# Build settings
theme: minima

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name
  wiki:
    output: true
    permalink: /:collection/:name
  research:
    output: true
    permalink: /:collection/:name

# Default front matter
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "page"
